#!/usr/bin/env php
<?php

use Codesvault\WPseeder\Cli\CliManager;

if (! empty($argv[1]) && 'seeder' === $argv[1]) {
	require_once './vendor/autoload.php';
	$argv[1] = ! empty($argv[2]) ? $argv[2] : $argv[1];

	new CliManager($argv);
}
